language: scala

scala:
- 2.12.8
- 2.13.0

jdk:
- openjdk8

branches:
  only:
  - master

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot

script: "sbt clean coverage test"
after_success: "sbt coverageReport coveralls"
